dbt_training_dw:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin
      password: admin
      port: 5432
      dbname: dbt_training
      schema: dbt_tr_dev
      threads: 1
      keepalives_idle: 0 
      connect_timeout: 10
    prod:
      type: postgres
      host: localhost
      user: admin
      password: admin
      port: 5432
      dbname: dbt_training
      schema: dbt_tr_prod
      threads: 1
      keepalives_idle: 0 
      connect_timeout: 10
